[Model] Transformer CN comment.
Mixture-AI/meta-llama-explain pull request #19
Opened 2024-05-21 14:42 UTC by NANWOOD

## Description

Transformer CN comment.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the `lint.sh` to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] Code is well-documented.
- [ ] Related issue is referred in this PR.

## Changes

2024-05-22 06:11 UTC, keli-wen requested changes

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # ? 暂时搁置
File an issue and add a [TODO] tag to refer this issue.

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +        """执行 Transformer 模型的前向过程.
```suggestion
        """执行 Transformer 模型的前向传播.
```

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +        # 根据输入的 token 索引计算对应的 embedding
```suggestion
        # 根据输入的 token 索引计算对应的 embedding.
```

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +        # 根据输入的 token 索引计算对应的 embedding
Miss the `[Shape]` comment.

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # 表示每个 token 只能使用当前 token 以及已经处理过的 token 的信息.
How about add a simple matrix here for clarity.
```
# e.g. mask matrix:
# ┌         ┐
# │ 0 -∞ -∞ │
# │ 0  0 -∞ │
# │ 0  0  0 │
# └         ┘
```

2024-05-22 06:11 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # 由于使用了 key-value caching, 我们只需要为新序列计算 attention scores.
💎💎💎The statement need to refine. And I think add some newlines will have better read experience.

2024-05-23 18:35 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 取出 KV-Cache 中 key 和 value 的缓存.
Just typos.
```suggestion
```

2024-05-23 18:36 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 若 n_kv_heads < n_heads, 则在 n_kv_heads 维度上进行重复扩充
Seems necessary, I will do it later.

2024-05-23 18:37 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # [Shape] scores: (batch_size, n_local_heads, seqlen, cache_len + seqlen)
```suggestion
```

2024-05-23 18:37 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 若存在 mask, 则对 attention scores 执行加法操作将 masked 部分置为 -inf.
```suggestion
        # [Shape] scores: (batch_size, n_local_heads, seqlen, cache_len + seqlen)
        # 若存在 mask, 则对 attention scores 执行加法操作将 masked 部分置为 -inf.
```

2024-05-23 18:39 UTC, NANWOOD commented on llama/model_cn_comment.py
>          hidden_dim = multiple_of * (
Seems this is already stated in the args section.

2024-05-23 18:40 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            layer_id (int): 网络层的标记符.
```suggestion
            layer_id (int): 网络层的标识符.
```

2024-05-23 18:41 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        """执行 TransformerBlock 的前向过程.
Seems not necessary.

2024-05-23 18:41 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            mask (torch.Tensor, optional): 计算 attention 时的遮罩. 默认设为 None.
```suggestion
            mask (torch.Tensor, optional): 计算 attention 时的 mask. 默认设为 None.
```
"遮罩" seems official translation.

2024-05-23 18:50 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            # 表示每个 token 只能使用当前 token 以及已经处理过的 token 的信息.
```suggestion
            # 表示每个 token 只能使用当前 token 以及已经处理过的 token 的信息.
            # e.g. mask matrix:
            # ┌         ┐ 
            # │ 0 -∞ -∞ │
            # │ 0  0 -∞ │ 
            # │ 0  0  0 │
            # └         ┘
```

2024-05-28 16:20 UTC, NANWOOD commented on llama/model_cn_comment.py
>          scores = torch.matmul(xq, keys.transpose(2, 3)) / math.sqrt(
```suggestion
        # [Shape] scores: (batch_size, n_local_heads, seqlen, cache_len + seqlen)
        scores = torch.matmul(xq, keys.transpose(2, 3)) / math.sqrt(
```

2024-05-28 16:21 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # [Shape] scores: (batch_size, n_local_heads, seqlen, cache_len + seqlen)
```suggestion
```

2024-05-28 16:38 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            n_layers (int): 模型中的层数.
```suggestion
            n_layers (int): 模型中 transformer block 的层数.
```

2024-05-28 16:43 UTC, NANWOOD commented on llama/model_cn_comment.py
>          hidden_dim = multiple_of * (
```suggestion
        # 保证 hidden_dim 为 multiple_of 的整数倍.
        hidden_dim = multiple_of * (
```

2024-05-29 09:48 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 使 query, key, value 的尺寸匹配.
```suggestion
        # 使 query, key, value 的尺寸匹配.
        # Q: 为什么会出现 n_kv_heads < n_heads 的情况？
        # A: 当 transformer 层采用 Grouped-Query Attention 时会出现 n_kv_heads < n_heads 的情况.
        # 即多个 query head 共享一对 key head 和 value head, 来减小 KV-Cache, 因此 n_heads 一定能被 n_kv_heads 整除. 
```

2024-05-29 09:52 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            x (torch.Tensor): 输入张量.
```suggestion
            x (torch.Tensor): 输入张量. Shape: (batch_size, seqlen, dim)
```

2024-05-29 09:55 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 残差计算 attention.
```suggestion
        # 残差计算 attention.
        # [Shape] h: (batch_size, seqlen, dim)
```

2024-05-29 09:55 UTC, NANWOOD commented on llama/model_cn_comment.py
> +        # 残差计算 FeedForward.
```suggestion
        # 残差计算 FeedForward.
        # [Shape] out: (batch_size, seqlen, dim)
```

2024-05-29 11:38 UTC, keli-wen requested changes

2024-05-29 11:38 UTC, keli-wen commented on llama/model_cn_comment.py
> +        # 即多个 query head 共享一对 key head 和 value head, 来减小 KV-Cache, 因此 n_heads 一定能被 n_kv_heads 整除.
Why can we say "一定"? Any proof?

2024-05-29 11:38 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # ? 暂时搁置
Please remember to add a [TODO] tag to refer the issue.

2024-05-30 09:18 UTC, NANWOOD commented on llama/model_cn_comment.py
> +            # ? 暂时搁置
```suggestion
            # ? 暂时搁置
            # [TODO] https://github.com/Mixture-AI/meta-llama-explain/issues/23#issue-2322926483
```

2024-05-30 09:42 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # 由于使用了 key-value caching, 我们只需要为新序列计算 attention scores.
How about:

```
# ┌─────────────────────────────────────────────────────────┐
# │ > mask maxtirx visualization                            │
# │                                                         │
# │                                     hstack              │
# │                                       ↓                 │
# │            ↙ [0][0][0][0][0][0][0][0] | [0][x][x][x][x] │
# │           ↙  [0][0][0][0][0][0][0][0] | [0][0][x][x][x] │
# │ seq_len(5) ← [0][0][0][0][0][0][0][0] | [0][0][0][x][x] │
# │           ↖  [0][0][0][0][0][0][0][0] | [0][0][0][0][x] │
# │            ↖ [0][0][0][0][0][0][0][0] | [0][0][0][0][0] │
# │                                    ↑     ↘  seq_len  ↙  │
# │                               cache_len(8)              │
# │                                                         │
# │ x: denote the -inf value (masked value)                 │
# └─────────────────────────────────────────────────────────┘
```

2024-05-30 09:48 UTC, keli-wen commented on llama/model_cn_comment.py
> +            # 尺寸为 (seqlen, start_pos) 的全零矩阵即可.
```suggestion
            # 尺寸为 (seqlen, start_pos) 的全零矩阵即可.
            # ┌─────────────────────────────────────────────────────────┐
            # │ > mask maxtirx visualization                            │
            # │                                                         │
            # │                                     hstack              │
            # │                                       ↓                 │
            # │            ↙ [0][0][0][0][0][0][0][0] | [0][x][x][x][x] │
            # │           ↙  [0][0][0][0][0][0][0][0] | [0][0][x][x][x] │
            # │ seq_len(5) ← [0][0][0][0][0][0][0][0] | [0][0][0][x][x] │
            # │           ↖  [0][0][0][0][0][0][0][0] | [0][0][0][0][x] │
            # │            ↖ [0][0][0][0][0][0][0][0] | [0][0][0][0][0] │
            # │                                    ↑     ↘  seq_len  ↙  │
            # │                               cache_len(8)              │
            # │                                                         │
            # │ x: denote the -inf value (masked value)                 │
            # └─────────────────────────────────────────────────────────┘
```

2024-05-30 09:49 UTC, keli-wen reviewed
LGTM

2024-05-30 09:50 UTC, keli-wen approved these changes

2024-05-30 09:51 UTC, merged